[package]
name   ="frontend"
version="0.1.0"
edition="2021"

[dependencies]
client-side-prover={ path="../prover" }

serde      ={ workspace=true }
serde_json ={ workspace=true }
thiserror  ={ workspace=true }
tracing    ={ workspace=true }
hex               ={ workspace=true }
ff                ={ workspace=true }
bellpepper-core   ={ workspace=true }
halo2curves       ={ workspace=true }

byteorder ={ workspace=true }
num-bigint={ workspace=true }
itertools ={ workspace=true }
bincode={ workspace=true }

# noir
acvm     ={ git="https://github.com/noir-lang/noir", rev="v1.0.0-beta.2" }
ark-bn254="0.5"

#- Wasm target configuration ----------------------------------------------------------------------#
[target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen  ="0.6.5"
wasm-bindgen        ="0.2.87"
js-sys              ="0.3.64"
wasm-bindgen-futures="0.4.37"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
circom_witnesscalc={ git="https://github.com/pluto/circom-witnesscalc" } # Fork is needed apparently??

[dev-dependencies]
tracing-test="0.2.5"
tempdir     ="0.3.7"
tokio = { version = "1.43", features = ["full"] }

[features]
verify-steps=[]
timing      =[]
