name: rust

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install tools
        run: |
          cargo binstall --no-confirm cargo-udeps taplo-cli

      - name: Run tests
        run: cargo test --all

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all

      - name: Check unused dependencies
        run: cargo udeps

      - name: Check TOML formatting
        run: taplo fmt --check 